### ISSUE TITLE
Should validate labels

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-incubator/zalando-deploy-cli#21]
The cli should validate the required labels:

* `application`
* `version`
* `release`
* `stage`?

**Comment by hjacobs** [comment]
Most importantly the Kubernetes resource name needs to comply with `DNS_SUBDOMAIN`, see https://github.com/kubernetes/kubernetes/blob/1dfd64f4378ad9dd974bbfbef8e90127dce6aafe/pkg/api/v1/types.go#L53
