### ISSUE TITLE
HostedZoneName in templating

### ISSUE THREAD

**Issue by juhmelo** [zalando-incubator/zalando-deploy-cli#38]
Currently the HostedZoneName `cluster-name.zalan.do` is hardcoded in manifests, and it is repeated in several places:

```
RDSDNSEntry:
    Properties:
      Name: "{{ application }}-db.hackweek-test.zalan.do."
      HostedZoneName: hackweek-test.zalan.do.
```

It would be nice if zdeploy automatically substituted a placeholder in templates since it can get the information from the cluster registry. This way manifests would not have to be changed depending on which cluster they are being deployed on:

```
RDSDNSEntry:
    Properties:
      Name: "{{ application }}-db.{{ hosted-zone-name }}."
      HostedZoneName: {{ hosted-zone-name }}.
```

**Comment by hjacobs** [comment]
I think this issue belongs to the Jenkins deploy pipeline as this CLI just passes thru template variables.

**Comment by juhmelo** [comment]
Typically yes, and it should be overwritten if it is provided by the deploy pipeline. 
However, the motivation for doing this in the CLI side:

- CLI already makes a call to cluster-registry. This would have to be added in pipeline.
- CLI is configured for one cluster at a time, and the hosted zone name is cluster specific.
- Makes using the CLI without the pipeline nicer, as adding this template variable by hand would probably just introduce a chance of error.

**Comment by juhmelo** [comment]
Closing this, since the zone name cannot be fetched from the cluster registry as I assumed.
