### ISSUE TITLE
scaling does not work with multiple old deployments

### ISSUE THREAD

**Issue by juhmelo** [zalando-incubator/zalando-deploy-cli#8]
Had a situation where I had multiple old deployments because of failed pipelines.
Pipeline output:
`https://deploy01.hackweek.zalan.do/job/Deployments/job/donald-trump/job/deploy/28/console`

The new deployment is `nginx-test-asdfgh-28`

```
Scaling deployment nginx-test-wqerrewq-27 to 2 replicas..
Scaling deployment nginx-test-qwerty-26 to 0 replicas..
Scaling deployment nginx-test-asdfgh-28 to 2 replicas..
```

for some reason an old deployment is scaled to 2 replicas.

**Comment by hjacobs** [comment]
Should be fixed with #10
